// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gIRrc-05q80uUMzBXZe7EheZKOJBG1Q',
    appId: '1:794737608140:android:2fb12f436f092794a88969',
    messagingSenderId: '794737608140',
    projectId: 'painting-by-numbers-181cd',
    storageBucket: 'painting-by-numbers-181cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtvjGK282stZ6cQBuGTX0-xoW7RGo0Wgc',
    appId: '1:794737608140:ios:e2dd1a57406379b4a88969',
    messagingSenderId: '794737608140',
    projectId: 'painting-by-numbers-181cd',
    storageBucket: 'painting-by-numbers-181cd.firebasestorage.app',
    iosClientId:
        '794737608140-0k1qjfqirgvf0ghbqmmthhidbdqe64g8.apps.googleusercontent.com',
    iosBundleId: 'com.eliahu.paitingByNumbers',
  );
}
