// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<VectorizationResult> vectorizeImageToSvg({
  required List<int> imageBytes,
  required int colors,
}) => RustLib.instance.api.crateApiSimpleVectorizeImageToSvg(
  imageBytes: imageBytes,
  colors: colors,
);

class PaletteEntry {
  final U8Array3 rgb;
  final String hex;

  const PaletteEntry({required this.rgb, required this.hex});

  @override
  int get hashCode => rgb.hashCode ^ hex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaletteEntry &&
          runtimeType == other.runtimeType &&
          rgb == other.rgb &&
          hex == other.hex;
}

class U8Array3 extends NonGrowableListView<int> {
  static const arraySize = 3;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array3(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array3.init() : this(Uint8List(arraySize));
}

class VectorizationResult {
  final String svgContent;
  final List<PaletteEntry> palette;

  const VectorizationResult({required this.svgContent, required this.palette});

  @override
  int get hashCode => svgContent.hashCode ^ palette.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VectorizationResult &&
          runtimeType == other.runtimeType &&
          svgContent == other.svgContent &&
          palette == other.palette;
}
